pipeline {
    agent any
    stages {
        stage('Update Packages') {
            steps {
                script {
                    // Update the package list
                    sh 'apt-get update'
                    sh 'apt-get install -y libpq-dev'
                }
            }
        }
        stage('Install Python') {
            steps {
                // Install Python and pip
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    // Clone the Git repository
                    git branch: 'main', url: 'https://github.com/AnkushGuptaQA/dqe-automation'
                }
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Create a virtual environment
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r PyTestDQFramework/requirements.txt
                    '''
                }
            }
        }
        stage('Run Pytest') {
            steps {
                sh '''
                    cd PyTestDQFramework
                    . venv/bin/activate
                    mkdir -p Test_Reports
                    pytest tests/dqchecks/parquet_files --html=Test_Reports/report.html --self-contained-html
                '''
            }
        }
        stage('Publish HTML Report') {
            steps {
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'PyTestDQFramework/Test_Reports',
                    reportFiles: 'report.html',
                    reportName: 'Pytest Report'
                ])
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}


